### ISSUE TITLE
Delayed audio

### ISSUE THREAD

**Issue by EdgarMP** [aschober/vinyl-cast#12]
Hi, I am using the generated APK from the repo, when using it through UFO202 it seems to be delay (like 5 sec), I can say it by scratching the vinyl, but if I play it through the phone speaker the delay is minimum, can it be the UFO202 the problem or network related?

**Comment by aschober** [comment]
Hey @EdgarMP  -- 

I've looked at this quite a bit as well trying to optimize it, but unfortunately in my testing, the delay seems primarily due to buffering on the Chromecast. You can try it out yourself by opening a browser pointed at the URL and see that the browser media player still has a bit of delay (~1secs) but not as much as a Chromecast at ~5secs. 

I have an update I'm working on that may optimize performance of the app a bit, but no significant improvement around the significant delay during playback on a Chromecast, and there's no way I've found to control/adjust the media player on the Chromecast to try to reduce how much audio data it buffers before starting playback. I end up using Chromecast grouping to do synced playback across multiple speakers (but need Cast devices at each speaker to do this). 

When casting, using uncompressed WAV audio has noticeably less delay compared to AAC audio so I suspect the buffering on Chromecast is based on bytes and not audio length.

Closing this issue for now but let me know if I can help with anything else.
